#api call for fetching all data

###
GET http://127.0.0.1:8000/api/restaurents/
Accept: application/json


###
POST http://127.0.0.1:8000/api/restaurents/
Content-Type: application/json

{
    "name":"Akshaya",
    "location":"Thrissu",
    "contact":"8362646358",
    "email":"akshaya@gmail.com",
    "rating":7.5
}

###
GET http://127.0.0.1:8000/api/restaurents/3/
Accept: application/json

# api call for updating data
###
PUT http://127.0.0.1:8000/api/restaurents/3/
Content-Type: application/json

{
    "name":"Akshaya",
    "location":"Thrissur",
    "contact":"8362646358",
    "email":"akshaya@gmail.com",
    "rating":7.3
}

#data deletion
###
DELETE http://127.0.0.1:8000/api/restaurents/2/
Accept: application/json


###
POST http://127.0.0.1:8000/api/restaurants/1/dish
Content-Type: application/json

{
    "name":"Idly",
    "description":"idly vada",
    "price":50,
    "quantity":1
}

###
GET http://127.0.0.1:8000/api/3/
Accept: application/json

###
PUT http://127.0.0.1:8000/api/3/
Content-Type: application/json

{
    "name": "Ghee Roast",
    "description": "with vada",
    "price": "150.00",
    "quantity": 2
}

###
DELETE http://127.0.0.1:8000/api/3/
Accept: application/json